## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
matrix:
  - PYTHON=Conda-python
matrix:
  allow_failures:
    - julia: nightly
#git:
#  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
env:
  - PYTHON=""
before_install:
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda;  Conda.add("python==2.7.13"); Conda.add("matplotlib"); Conda.add("scikit-learn"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'
script:
  - LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so
  - julia -e 'Pkg.clone(pwd()); Pkg.build("LightML"); Pkg.test("LightML"; coverage=true)'
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LightML"); Pkg.test("LightML"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LightML")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LightML")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

